on: 
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: A job to update sets and cards
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set PAT token
        id: PAT
        run: echo "::set-output name=PAT::$ACCESS_TOKEN"
      - name: Get Sets action step
        id: sets
        uses: dannyverdel/pokemon-data@v1.0.3
        with:
          token: ${{steps.PAT.outputs.PAT}}
