on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    name: A job to update sets and cards
    steps:
      - name: Hello world action step
        id: hello
        uses: dannyverdel/pokemon-data@v1.1
        with:
          update: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get sets and cards
        run: echo "${{ steps.hello.outputs }}"
