on: 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: A job to update sets and cards
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get Sets action step
        id: sets
        uses: dannyverdel/pokemon-data@v1.8
        with:
          token: "{{$ACCESS_TOKEN}}"
